### ISSUE TITLE
Certificate issue

### ISSUE THREAD

**Issue by IzzySoft** [16arpi/Fox-RSS#18]
A scan ([see here](https://gitlab.com/IzzyOnDroid/repo/-/issues/477) for details and background) just revealed the APKs at your releases are signed using a debug key. As that has security implications, may I ask you to please switch to a proper release key, and provide the corresponding APK signed with it? Thanks in advance!

**Comment by IzzySoft** [comment]
As there's no response at all I assume the project is no longer maintained, so the issue cannot be solved, I've hence removed the app from [my repo](https://apt.izzysoft.de/fdroid) now. Should you pick up development again and have a properly signed APK ready be welcome to let me know, so I can see to reestablish the listing. Thanks!

**Comment by 16arpi** [comment]
Sorry for playing dead most of the time... Thank you for your interest in my application, but unfortunately I think you're right: since I'm no longer running this project, I think the best thing to do is to remove it from your repository. I'll try to sort out all the problems one day! See you soon :)

**Comment by IzzySoft** [comment]
Thanks @16arpi – and my offer stands: reach out to me the day you're ready, and I'll see to reestablish your app here. Metadata are still kept (just archived), so it can be done easily and quickly.
